# Generated by Django 5.1.4 on 2025-01-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
