# Generated by Django 5.1.4 on 2025-01-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='time_out',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='time_in',
            new_name='start_time',
        ),
    ]
