# Generated by Django 5.1.4 on 2025-01-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_dailyreport_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
