# Generated by Django 5.1.4 on 2025-01-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('designation', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.TextField()),
                ('remarks', models.CharField(choices=[('Completed', 'Completed'), ('Uncompleted', 'Uncompleted'), ('Other', 'Other')], max_length=20)),
                ('other_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextDayPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('coordination', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('to_do', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.RemoveField(
            model_name='department',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='department',
            name='supervisors',
            field=models.ManyToManyField(limit_choices_to=models.Q(('role', 'supervisor')), related_name='supervised_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'supervisor')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='intern_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.internprofile'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='supervisor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='nextdayplanning',
            name='intern_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.internprofile'),
        ),
        migrations.AddField(
            model_name='nextdayplanning',
            name='supervisor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.supervisorprofile'),
        ),
    ]
