# Generated by Django 5.1.4 on 2025-01-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_rename_time_out_dailyreport_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanagementform',
            old_name='supervisor_profile',
            new_name='supervisor',
        ),
    ]
