# Generated by Django 5.1.4 on 2025-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_dailyactivity_nextdayplanning_delete_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='date',
            field=models.DateField(),
        ),
    ]
