# Generated by Django 5.1.4 on 2025-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_dailyreport_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='total_hours',
            field=models.TextField(default='06:20'),
        ),
    ]
