# Generated by Django 5.1.4 on 2025-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_user_phone_no_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pu_reg_no',
            field=models.CharField(default='1-12-2024', max_length=20),
        ),
    ]
