# Generated by Django 5.1.4 on 2025-01-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_rename_supervisor_profile_projectmanagementform_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanagementform',
            name='supervisor',
        ),
    ]
