# Generated by Django 5.1.4 on 2025-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_dailyactivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextdayplanning',
            name='date',
            field=models.DateField(),
        ),
    ]
