# Generated by Django 5.1.4 on 2025-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_user_pu_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
