# Generated by Django 5.1.4 on 2025-01-22 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_remove_projectmanagementform_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanagementform',
            name='team_member',
        ),
        migrations.AddField(
            model_name='projectmanagementform',
            name='team_member',
            field=models.ManyToManyField(null=True, related_name='team_member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
