# Generated by Django 5.1.4 on 2025-01-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_nextdayplanning_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='designation',
        ),
    ]
