# Generated by Django 5.1.4 on 2025-01-22 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_remove_projectmanagementform_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagementform',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='team_member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
