# Generated by Django 5.1.4 on 2025-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_dailyreport_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='time_in',
            field=models.TimeField(default='10:30:AM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='time_out',
            field=models.TimeField(default='05:00:PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interndailyactivity',
            name='end_time',
            field=models.TimeField(default='05:00:PM'),
        ),
        migrations.AlterField(
            model_name='interndailyactivity',
            name='start_time',
            field=models.TimeField(default='10:30:AM'),
        ),
        migrations.AlterField(
            model_name='internnextdayplanning',
            name='end_time',
            field=models.TimeField(default='05:00:PM'),
        ),
        migrations.AlterField(
            model_name='internnextdayplanning',
            name='start_time',
            field=models.TimeField(default='10:30:AM'),
        ),
        migrations.AlterField(
            model_name='supervisordailyactivity',
            name='end_time',
            field=models.TimeField(default='05:00:PM'),
        ),
        migrations.AlterField(
            model_name='supervisordailyactivity',
            name='start_time',
            field=models.TimeField(default='10:30:AM'),
        ),
        migrations.AlterField(
            model_name='supervisornextdayplanning',
            name='end_time',
            field=models.TimeField(default='05:00:PM'),
        ),
        migrations.AlterField(
            model_name='supervisornextdayplanning',
            name='start_time',
            field=models.TimeField(default='10:30:AM'),
        ),
    ]
