# Generated by Django 5.1.4 on 2025-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_supervisorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pu_reg_no',
            field=models.CharField(blank=True, default='1-12-2024', max_length=20),
        ),
    ]
