# Generated by Django 5.1.4 on 2025-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_alter_user_pu_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internprofile',
            name='pu_reg_no',
            field=models.CharField(blank=True, default='1-12-2024', max_length=20),
        ),
    ]
