# Generated by Django 5.1.4 on 2025-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_alter_dailyreport_time_in_alter_dailyreport_time_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='total_hours',
            field=models.IntegerField(default=6.2),
        ),
    ]
