# Generated by Django 5.1.4 on 2025-01-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_remove_dailyactivity_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextdayplanning',
            name='intern_profile',
        ),
        migrations.RemoveField(
            model_name='nextdayplanning',
            name='supervisor_profile',
        ),
        migrations.CreateModel(
            name='InternDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.TextField()),
                ('remarks', models.CharField(choices=[('Completed', 'Completed'), ('Uncompleted', 'Uncompleted'), ('Other', 'Other')], max_length=20)),
                ('other_remarks', models.TextField(blank=True, null=True)),
                ('intern_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.internprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternNextDayPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('coordination', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('to_do', models.TextField()),
                ('intern_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.internprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.TextField()),
                ('remarks', models.CharField(choices=[('Completed', 'Completed'), ('Uncompleted', 'Uncompleted'), ('Other', 'Other')], max_length=20)),
                ('other_remarks', models.TextField(blank=True, null=True)),
                ('supervisor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.supervisorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorNextDayPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('coordination', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('to_do', models.TextField()),
                ('supervisor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.supervisorprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
        migrations.DeleteModel(
            name='NextDayPlanning',
        ),
    ]
