# Generated by Django 5.1.4 on 2025-01-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_alter_projectmanagementform_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagementform',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_project', to='usermanagement.supervisorprofile'),
        ),
    ]
