# Generated by Django 5.1.4 on 2025-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_remove_nextdayplanning_intern_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='it', max_length=20),
            preserve_default=False,
        ),
    ]
