# Generated by Django 5.1.4 on 2025-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_alter_dailyreport_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
