# Generated by Django 5.1.4 on 2025-01-21 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_alter_dailyreport_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('supervisor', 'Supervisor'), ('students', 'students')], default='intern', max_length=20),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_field', models.URLField(blank=True, help_text='Enter a valid image URL.', null=True)),
                ('full_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_no', models.CharField(blank=True, help_text='Enter phone number in international format, e.g., +123456789.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=255)),
                ('parents_info', models.CharField(default={'Father Name=Hari', 'Mother Name=Sita'}, max_length=200)),
                ('par_phone_no', models.CharField(max_length=15)),
                ('username', models.OneToOneField(limit_choices_to=models.Q(('role', 'students')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=30)),
                ('started_date', models.DateField()),
                ('division_gpa', models.CharField(blank=True, help_text='Enter the division or GPA as a string.', max_length=100, null=True)),
                ('college_university', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.students')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provience', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('mc_rm', models.CharField(help_text='Enter the name of metropolitan/district name', max_length=30)),
                ('ward_no', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.students')),
            ],
        ),
        migrations.CreateModel(
            name='IntrestedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrested_courses', models.CharField(choices=[('Accounting', 'Accounting'), ('Office Package', 'Office Package'), ('Graaphic design', 'Graaphic design'), ('Web Develpoment', 'Web Develpoment'), ('SEO', 'SEO'), ('English Language', 'English Language'), ('video Editing', 'video Editing'), ('Others', 'Others')], max_length=30)),
                ('suitable_time', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.students')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provience', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('mc_rm', models.CharField(help_text='Enter the name of metropolitan/district name', max_length=30)),
                ('ward_no', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.students')),
            ],
        ),
    ]
