# Generated by Django 5.1.4 on 2025-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='first_name',
            field=models.CharField(default='Aashish', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='last_name',
            field=models.CharField(default='Pradhan', max_length=20),
            preserve_default=False,
        ),
    ]
