# Generated by Django 5.1.4 on 2025-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_alter_projectmanagementform_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('supervisor', 'Supervisor'), ('employee', 'employee'), ('students', 'Students'), ('superuser', 'Superuser')], default='intern', max_length=20),
        ),
    ]
