# Generated by Django 5.1.4 on 2025-01-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employesprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('role', 'Employee')), on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
