# Generated by Django 5.1.4 on 2025-01-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_alter_user_role_students_studentacademicdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img_field',
            field=models.CharField(blank=True, help_text='Enter a valid image URL.', max_length=200, null=True),
        ),
    ]
