# Generated by Django 5.1.4 on 2025-01-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_supervisorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.department'),
        ),
    ]
