# Generated by Django 5.1.4 on 2025-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_alter_students_img_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pu_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('supervisor', 'Supervisor'), ('students', 'students'), ('superuser', 'Superuser')], default='intern', max_length=20),
        ),
    ]
