# Generated by Django 5.1.5 on 2025-01-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_alter_employesprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='intern',
            field=models.ForeignKey(limit_choices_to={'user': 'usermanagement.User'}, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.internprofile'),
        ),
    ]
